# Enable the build cache to save time by reusing outputs produced by other successful builds.
# https://docs.gradle.org/current/userguide/build_cache.html
org.gradle.caching=true
# Enable the configuration cache to reuse the build configuration and enable parallel task execution.
# (Note that some plugins may not yet be compatible with the configuration cache.)
# https://docs.gradle.org/current/userguide/configuration_cache.html
org.gradle.configuration-cache=true
# Give Gradle daemon enough heap to avoid frequent GC pauses
org.gradle.jvmargs=-Xmx2g -Xms512m -XX:MaxMetaspaceSize=1g -XX:+UseParallelGC
# Build subprojects in parallel when possible
org.gradle.parallel=true
