server:
  port: 8080

spring:
  application:
    name: otus-highload
  liquibase:
    url: jdbc:postgresql://localhost:5432/otus_highload
    user: otus
    password: otus_pass
    change-log: classpath:/db/changelog/db.changelog-master.xml

app:
  search:
    limit: 50
  datasource:
    pool-size: 25
    connection-timeout: 5000
    master:
      url: jdbc:postgresql://localhost:5432/otus_highload
      username: otus
      password: otus_pass
    slave:
      urls: jdbc:postgresql://localhost:5433/otus_highload,jdbc:postgresql://localhost:5434/otus_highload
      username: otus
      password: otus_pass

logging:
  structured:
    format:
      console: logstash

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0

