server:
  port: 8080

spring:
  application:
    name: otus-highload
  datasource:
    url: jdbc:postgresql://localhost:5432/otus_highload?rewriteBatchedInserts=true&stringtype=unspecified
    username: otus
    password: otus_pass
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 25
      connection-timeout: 5000
      data-source-properties:
        preparedStatementCacheQueries: 512
        preparedStatementCacheSizeMiB: 10
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

app:
  search:
    limit: 50

logging:
  structured:
    format:
      console: logstash

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0

