server:
  port: 8080

spring:
  application:
    name: otus-highload
  datasource:
    url: jdbc:postgresql://localhost:5432/otus_highload
    username: otus
    password: otus_pass
    driver-class-name: org.postgresql.Driver
  liquibase:
    change-log: classpath:/db/changelog/db.changelog-master.xml

logging:
  structured:
    format:
      console: logstash

management:
  endpoints:
    web:
      exposure:
        include: health, prometheus
  metrics:
    distribution:
      percentiles-histogram:
        http.server.requests: true
  tracing:
    sampling:
      probability: 1.0

